name: testNodeLatest

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run ldd
        npm run build --if-present
        npm test
      env:
        CI: true
